This program shows how to use SolAR framework and two modules (openCV and Tools) to perform a simple camera pose estimation based on a natural image marker.
In this exemple, the actual SolAR component implementations are loaded at runtime, and in the code we are using the abstract interface of the components.

To use it, you need to set the following parameters:

. a path to a file describing the natural image marker (.yml)
. a path to a file defining your camera calibration parameters (.yml)
. the camera number (if you don't know, try 0) or a path to a video

Example of use : SolARNaturalImageMarkerStatic.exe grafMarker.yml camera_calibration.yml 0

Examples of yml files are provided.
The natural image marker file indicates the marker size in defined i nthe same unit as the one used to calibrate your camera (meters, centimeters, etc.), as well as the path to the image defining your maker:
[source]
-----
%YAML:1.0
---
MarkerWidth: 0.285
MarkerHeight: 0.197
ImagePath: './graf1.png'
-----

Concerning the camera calibration file, you can use the one provided with this sample. Be aware that the provided camera calibration file is likely to mismatch your hardware, leading to awkward results. In case you want to use a  correct calibration, you can run the provided camera calibration software (see SolAR web page). It will output a calibration file in the correct format that you can use readily.

Notice that your working directory should be correctly set (in QT see Projects/run).
