This program shows how to use SolAR framework with two modules (Opencv and Tools) to perform a simple camera pose estimation based on a natural image marker.
In this example, the actual SolAR component implementations are specified at the build-time, but in the code we are using the abstract interfaces of your components. 
Careful ! We call that the static mode, though libraries are dynamically linked.
This is in contrast with the targeted final SolAR mode of operation where the SolAR component implementations will be loaded at run-time: this is the runtime mode, see the Solar web page.

Once it is compiled, via Qt or Visaul Studio, you can run it using three input parameters.  

. a path to a file describing the natural image marker (.yml)
. a path to a file defining your camera calibration parameters (.yml)
. either the ID of your camera (if you don't know, try 0) or a path to a video file

Example of use : SolARNaturalImageMarkerStatic.exe grafMarker.yml camera_calibration.yml 0

Examples of yml files are provided.
The natural image marker file indicates the marker size in defined i nthe same unit as the one used to calibrate your camera (meters, centimeters, etc.), as well as the path to the image defining your maker:
[source]
----
%YAML:1.0
---
MarkerWidth: 0.285
MarkerHeight: 0.197
ImagePath: './graf1.png'
---- 

Concerning the camera calibration file, you can use the one provided with this sample. Be aware that the provided camera calibration file is likely to mismatch your hardware, leading to awkward results. In case you want to use a  correct calibration, you can run the provided camera calibration software (see SolAR web page). It will output a calibration file in the correct format that you can use readily.

Notice that your working directory should be correctly set (in QT see Projects/run).

